apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: denfensor-testing
  name: denfensor-testing
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: denfensor-testing
    spec:
      containers:
      - args:
        - npm
        - test
        image: denfensor-testing
        name: denfensor-testing
        resources: {}
        volumeMounts:
        - mountPath: /usr/defensor/e2eTest/reports
          name: denfensor-testing-claim0
      restartPolicy: Always
      volumes:
      - name: denfensor-testing-claim0
        persistentVolumeClaim:
          claimName: denfensor-testing-claim0
status: {}
